### ISSUE TITLE
Getting a status 429 - Error creating new registration

### ISSUE THREAD

**Issue by CalebKing3** [rolodato/gitlab-letsencrypt#33] opened 2017-11-30 06:45 UTC
Hi @rolodato hope you can help on this one. 

This is my command, I am trying to https a subdomain url.

`gitlab-le --jekyll --path /public/ --email calebking3@gmail.com --repository veganeats/blog --token mytoken --domain blog.veganeats.recipes www.blog.veganeats.recipes`

This is a jekyll project. 

Was initially getting the following and would just increase time
`
Could not find challenge file. Retrying in 30s...
Could not find challenge file. Retrying in 1m...
Could not find challenge file. Retrying in 2m...
Could not find challenge file. Retrying in 4m...
`

then i looked at previous issues and added path to point to my public folder. 

.well-known/acme-challenge is found the public folder but since I've been testing im getting this

`
   Registration request failed: {
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new registration :: too many registrations for this IP",
  "status": 429
}
`

**Comment by rolodato** [comment] 2017-11-30 12:15
Hi @CalebKing3, this error is caused by hitting the Let's Encrypt registration rate limits from your IP address. The causes of this can vary, there's a lot of discussion in this thread for example: https://community.letsencrypt.org/t/unexpected-registration-rate-limiting-error/2157/30. It's a long shot, but disabling IPv6 might help if you're using it.

Were you getting any errors when trying to get the certificate? If you are still troubleshooting, you should use the `--staging` option so you can test without running into these rate limits. You should be able to use the staging environment even if you are rate-blocked in production.

**Comment by CalebKing3** [comment] 2017-11-30 19:34
I appreciate the quick response, when I was running the command to encrypt, the retry time would double, each time it couldn't find the challenge file. 

I've used this project on a simpler static landing page, completing the process within 4 minutes, but I was getting up to 16 mins for the current project. 

Is there anything wrong with my cmd?

**Comment by rolodato** [comment] 2017-11-30 22:44
By looking at the latest commit to your repository generated by this tool, you can see that the build is failing: https://gitlab.com/VeganEats/blog/commit/635afa636b91856fe3a564b2445254ad59ca450e

Since the build is failing, these files will never be made available publicly, which explains why the process is timing out. You should fix your repository's build and then try again. Use the `--staging` option to test, and when it's fixed you can remove it, just to make sure you don't get rate limited again.

Also, since you are using Jekyll, it should be fine to use `--path /`, since the public URL is determined by the YAML front matter in the challenge files and not the actual path inside the repository. For example [this file](https://gitlab.com/VeganEats/blog/blob/master/esEWpFQA67jCrDY1z55amyIMPZTRiWGEA85Tc41Bn6A) is uploaded to your repository's root directory but is available at the URL http://blog.veganeats.recipes/.well-known/acme-challenge/esEWpFQA67jCrDY1z55amyIMPZTRiWGEA85Tc41Bn6A.

Closing this as it's not an issue with this tool. Hope this helps!

**Closed as completed by rolodato** 2017-11-30 22:44 UTC

**Comment by CalebKing3** [comment] 2017-12-01 00:23
Thank you for pointing out the build failure. I got that fix. I am getting closer, but now getting this error. 

```
By using Let's Encrypt, you are agreeing to the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Uploaded challenge file, waiting for it to be available at http://blog.veganeats.recipes/.well-known/acme-challenge/0RSF74dQAYsGuIGiz6NNkzwu60g-2BZRjNUCrRv-7yk
Could not find challenge file. Retrying in 30s...
Could not find challenge file. Retrying in 1m...
Could not find challenge file. Retrying in 2m...
Could not find challenge file. Retrying in 4m...
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/le-acme-core/lib/get-certificate.js:135:22
    at Request._callback (/usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gitlab-letsencrypt/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ type: 'urn:acme:error:badNonce',
  detail: 'JWS has invalid anti-replay nonce i5R30g3SoGtHrC3hPegBddpowarjoHu-mggrM--j5_U',
  status: 400 }
JWS has invalid anti-replay nonce i5R30g3SoGtHrC3hPegBddpowarjoHu-mggrM--j5_U
```

any ideas?

**Comment by rolodato** [comment] 2017-12-01 10:32
I've never seen that error. Quick Googling suggests that the solution is to try again or to reduce the time of your build. The nonce is only valid for a few minutes, so if your build is taking too long it could be that it's expiring before the challenge file is made publicly available.
